# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='albumArtist',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='albumCover',
            new_name='cover',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='albumGenre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='album',
            old_name='albumTitle',
            new_name='title',
        ),
    ]
