# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_isfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='isFavorite',
        ),
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.FileField(upload_to=b''),
        ),
    ]
